---
title: |
  | \vspace{2cm} \LARGE{Project Proposal: ISyE 6414 (Dr. Yajun Mei) - Spring 2020}
author: "Samuel Garcia, Michael Szostak, Osman Ghandour, and Peter Williams"
date: "`r Sys.Date()`"
header-includes:
  - \usepackage{float}
  - \usepackage{caption} 
  - \usepackage{amsmath}
  - \captionsetup[table]{skip=8pt}
output:
  bookdown::pdf_document2: 
    toc: false
bibliography: proposal_bib.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::current_input(dir = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
suppressPackageStartupMessages(require(rmarkdown))
suppressPackageStartupMessages(require(bookdown))
suppressPackageStartupMessages(require(kableExtra))
```

# Project Description

According to the *World Health Organization*, @who2019 one person dies every 40 seconds from suicide. It is the second leading cause of death among teenages and adults aged 15-29 years. Despite the staggering number of suicides happening worldwide, just 38 governments worldwide have a national suicide prevention strategy. 

Each of these deaths are tragic, and sadly also preventable. For every suicide, there are many more attempts, and previous suicide attempts are the single most important predictor or risk factor for future suicide attempts. @stats2019 The possibility of prevention and the scale of the problem highlight the need for policy decision makers at the country level to understand the factors that contribute to suicide in their own nations, and also gain understanding about what contributes to in at a global level.  

The objective of our project is to analyze country level data related to suicide rates over the past ten years, and augment it with other country level data and metadata we can obtain to gain and understanding and better describe rising suicide rates worldwide. Our intentions are two-fold: 

1. To describe and identify measures and country level indicators that impact suicide rates at he country level to provide high level decision making support for leaders and authors of public policy related to mental health and suicide. This includes identifying factors and measures related to suicide prevention that are worth monitoring over time for those who manage health related planning activities and priorities.   
2. To discuss the process of collection and the sources of data related to suicide at the country level utilized as well as describing ancillary datasets that were employed to augment and enrich insights related to international differences in suicide rates. The goal here is to make further research and data analysis on this topic more accessible to other interested researchers and data analysts in the future. 


# Dataset Description: How and From Where

The core dataset we plan to rely on comes directly from the *World Health Organization* and is referenced below.  The key measure of interest for our study is the suicide rate by country, which is defined as, *the age-standardized suicide rate is a weighted average of the age-specific mortality rates per 100,000 persons, where the weights are the proportions of persons in the corresponding age groups of the WHO standard population.* @whodat2019 The data consists measures of suicides rates, as defined above, at the country level, for $183$ nations, broken out by gender, and standardized as describe above. These estimates of age-standardized suicide rates were taken in the year $2000$, $2010$, $2015$, and $2016$. This enables the data analyst to observe differences in rate estimates over time, allowing more context and benchmarking for the purposes of this analysis. 

In addition to relying on the core suicide rate statistics provided above, we also intend to append data at the country level, for corresponding measurement time periods from ancillary data sources, currently we are exploring including data related to: 

1. GDP per capita, as a high level measure of wealth, sourced from the *World Bank*
2. An education index, as made available from the *OECD*, the *Organization for Economic Co-operation and Development*
3. The female labor force participation rate, from the *United Nations Development Programme*  

# Scientific Research Questions To Address

Integrating data sourced from various programs, and data collection agencies detailed above, we plan to tackle our objectives by focusing research questions in the following areas:  

*1. Can we statistically confirm and identify which measures/indicators are best associated with suicide rate?*  
*2. What socioeconomic factors help describe suicide rates at the country level?*  
*3. Can we infer anything about particular country policies or factors contribute to suicide rates?*  
*4. Is it possible to recommend where researchers should begin or focus their studies in the future on this topic?*  

*Osman's note: with such an elementary analysis, any answer of ours for 3 and 4 would seem highly speculative and won't have much basis. we should discuss if/how we can actually answer these questions.

# Proposed Statistical Methods and Models 

We plan to rely on multiple linear regression as a mechanism to discover what variables contribute to describing the outcome of interest, along with their statistical significance. Our purpose in using this tool will be to describe the dataset intuitively, and identify statistical significance of particular explanatory variables on our outcome of interest. 

We also plan to explore using another generalized linear model, the poisson regression model, as our key response variable consists of count data (the number of suicides per 100,000 persons). Our plan is to use both of these models as a means to describe and test hypotheses related to variables that may contribute to suicide rates country by country across the globe. 

For both the multiple linear regression and the poisson regression models, we will use the F-Test and likelihood ratio test to determine how the model would perform if we dropped a certain parameter (make sure we can do this?)
  
*References*  
  



